# DAX Measures — Retail Sales Analytics
# Table: superstore_clean | Date table: Date
# ─────────────────────────────────────────────────────────────────────────────
#
# MEASURES LIST (24 total):
#   1. Total Revenue
#   2. Total Profit
#   3. Total Orders
#   4. Profit Margin %
#   5. Avg Discount %
#   6. Avg Shipping Days
#   7. Revenue YoY %
#   8. Profit YoY %
#   9. Revenue YTD
#  10. Revenue 3M Rolling Avg
#  11. Underperformer Flag
#  12. Latest Year Revenue YoY %
#  13. Profit PY
#  14. Product Rank by Sales          [NEW — Page 3]
#  15. Product Rank by Profit         [NEW — Page 3]
#  16. Is Top 10 Product               [NEW — Page 3]
#  17. Is Bottom 10 Product            [NEW — Page 3]
#  18. Total Customers                 [NEW — Page 5 support]
#  19. Avg Order Value                 [NEW — Page 5 support]
#  20. Orders per Customer             [NEW — Page 5 support]
#  21. Top Region by Margin Name/Value [NEW — Page 5 card]
#  22. Top Category by Profit Name/Value [NEW — Page 5 card]
#  23. Strongest YoY Growth Year/Value [NEW — Page 5 card]
#  24. Margin Risk Region Name/Value   [NEW — Page 5 card]
#
# ─────────────────────────────────────────────────────────────────────────────


# ══════════════════════════════════════════════════════
# 1. CORE KPI MEASURES
# ══════════════════════════════════════════════════════
# Used on: Page 1 (cards), Page 2 (table, bar), Page 3 (scatter, waterfall)

Total Revenue =
SUM(superstore_clean[sales])
-- Sums the sales column across all rows in current filter context.
-- Displayed on Page 1 card (12.64M total), Page 2 table, Page 3 treemap.


Total Profit =
SUM(superstore_clean[profit])
-- Sums profit across all rows. Can be negative for loss-making rows.
-- Used on Page 1 card (1.47M), Page 2 table, Page 3 waterfall.


Total Orders =
DISTINCTCOUNT(superstore_clean[order_id])
-- Counts unique order IDs. DISTINCTCOUNT used instead of COUNT
-- because multiple line items share the same order_id.
-- Displayed on Page 1 card (25K), Page 2 table.


Profit Margin % =
DIVIDE(
    SUM(superstore_clean[profit]),
    SUM(superstore_clean[sales]),
    0
)
-- DIVIDE safely handles division by zero (returns 0 instead of error).
-- Returns a decimal (0.1161 = 11.61%). Formatted as % in Measure tools.
-- Used on Page 1 matrix heatmap, Page 2 bar + table, Page 3 scatter.


Avg Discount % =
AVERAGE(superstore_clean[discount])
-- discount column stores values as decimals (0.2 = 20%).
-- Formatted as % in Measure tools.
-- Used on Page 2 table, Page 3 scatter X-axis.


Avg Shipping Days =
AVERAGE(superstore_clean[shipping_days])
-- shipping_days is a derived column created in etl.py:
--   shipping_days = ship_date - order_date (in days)
-- Used on Page 4 shipping bar chart.


# ══════════════════════════════════════════════════════
# 2. YoY GROWTH MEASURES
# ══════════════════════════════════════════════════════
# Used on: Page 1 (card additional value), Page 4 (combo chart line)

Revenue YoY % =
VAR CurrentYear = MAX(superstore_clean[order_year])
VAR CurrentRev  = [Total Revenue]
VAR PriorRev    =
    CALCULATE(
        [Total Revenue],
        superstore_clean[order_year] = CurrentYear - 1
    )
RETURN
    IF(PriorRev = 0, BLANK(), DIVIDE(CurrentRev - PriorRev, PriorRev))
-- Uses order_year from the fact table directly — no Date table dependency.
-- Returns decimal (0.27 = 27%). Formatted as % in Measure tools.
-- In Page 4 combo chart: MAX(order_year) picks each bar's year individually.
-- In Page 1 card: MAX(order_year) = 2014, so shows 2014 vs 2013 growth.


Profit YoY % =
VAR CurrentYear  = MAX(superstore_clean[order_year])
VAR CurrentProfit = [Total Profit]
VAR PriorProfit   =
    CALCULATE(
        [Total Profit],
        superstore_clean[order_year] = CurrentYear - 1
    )
RETURN
    IF(PriorProfit = 0, BLANK(), DIVIDE(CurrentProfit - PriorProfit, PriorProfit))
-- Same logic as Revenue YoY % but applied to profit.
-- Used on Page 1 Total Profit card as additional value label.


# ══════════════════════════════════════════════════════
# 3. TIME INTELLIGENCE MEASURES
# ══════════════════════════════════════════════════════
# Used on: Page 4 (Revenue YTD card)
# Requires: Date table marked as date table with active relationship
#           to superstore_clean[order_date]

Revenue YTD =
TOTALYTD([Total Revenue], 'Date'[Date])
-- Accumulates Total Revenue from Jan 1 to the last date in current context.
-- When no year slicer is selected: returns full dataset total (4.30M = 2014 full year).
-- When year = 2013 selected: returns 2013 cumulative revenue.
-- Requires Date table relationship to be active.


# ══════════════════════════════════════════════════════
# 4. TREND MEASURES
# ══════════════════════════════════════════════════════
# Used on: Page 1 line chart (second Y-axis line)

Revenue 3M Rolling Avg =
VAR CurrentMonth = MAX(superstore_clean[order_yearmonth])
VAR Last3Months =
    FILTER(
        ALL(superstore_clean[order_yearmonth]),
        superstore_clean[order_yearmonth] <= CurrentMonth &&
        superstore_clean[order_yearmonth] >=
            FORMAT(
                EDATE(DATEVALUE(CurrentMonth & "-01"), -2),
                "YYYY-MM"
            )
    )
RETURN
    CALCULATE([Total Revenue], Last3Months) / 3
-- Works on order_yearmonth text column (e.g. "2013-07") — no Date table needed.
-- For each month point on the chart, looks back 2 months and averages 3 months.
-- EDATE shifts the date back by 2 months; FORMAT converts back to "YYYY-MM" string.
-- Smooths out monthly spikes to reveal the underlying revenue trend.


# ══════════════════════════════════════════════════════
# 5. CONDITIONAL FORMATTING MEASURES
# ══════════════════════════════════════════════════════
# Used on: Page 2 bar chart (red/green colouring by region performance)

Underperformer Flag =
VAR OverallAvg =
    CALCULATE(
        DIVIDE(SUM(superstore_clean[profit]), SUM(superstore_clean[sales])) * 100,
        REMOVEFILTERS(superstore_clean[region])
    )
VAR CurrentMargin = [Profit Margin %] * 100
RETURN
    IF(CurrentMargin < OverallAvg, "Underperformer", "On Target")
-- OverallAvg: removes region filter to get the global average margin (11.61%).
-- CurrentMargin: profit margin for the region currently in filter context.
-- Returns "Underperformer" if region margin < global average, else "On Target".
-- Used in Page 2 bar chart conditional formatting rules:
--   "Underperformer" → Red | "On Target" → Green


# ══════════════════════════════════════════════════════
# 6. ADDITIONAL MEASURES (Page 1 KPI Cards)
# ══════════════════════════════════════════════════════

Latest Year Revenue YoY % =
VAR LatestYear  = MAXX(ALL(superstore_clean[order_year]), superstore_clean[order_year])
VAR CurrentRev  = CALCULATE([Total Revenue], superstore_clean[order_year] = LatestYear)
VAR PriorRev    = CALCULATE([Total Revenue], superstore_clean[order_year] = LatestYear - 1)
RETURN
    DIVIDE(CurrentRev - PriorRev, PriorRev)
-- MAXX(ALL(...)) ignores all slicers and always finds the absolute latest year (2014).
-- This is different from Revenue YoY % which uses MAX() — that responds to slicer context.
-- Here we hardlock to 2014 vs 2013 so the Page 1 card always shows the most recent growth.
-- Why not just use Revenue YoY %? Because on Page 1 with no year slicer selected,
-- MAX(order_year) becomes context-dependent and can return wrong values.
-- Used on: Page 1 Total Revenue card as additional value label.


Profit PY =
CALCULATE(
    [Total Profit],
    superstore_clean[order_year] = MAX(superstore_clean[order_year]) - 1
)
-- Calculates Total Profit for the prior year relative to current filter context.
-- MAX(order_year) - 1 shifts back exactly one year.
-- Example: if year slicer = 2013, returns 2012 profit.
-- If no slicer selected, MAX = 2014 so returns 2013 profit.
-- Used as a reference/target value to compare against current year profit.
-- Used on: Page 1 Total Profit card as additional value or tooltip context.


# ══════════════════════════════════════════════════════
# 7. PRODUCT RANKING MEASURES  [NEW]
# ══════════════════════════════════════════════════════
# Used on: Page 3 — Top 10 / Bottom 10 Products visuals

Product Rank by Sales =
RANKX(
    ALL(superstore_clean[product_name]),
    CALCULATE([Total Revenue]),
    ,
    DESC
)
-- Ranks every product by total revenue, highest first.
-- ALL() removes any existing product filter so ranking is computed
-- across the full product list, not just whatever's currently visible.
-- Used with a Top N filter (Top 10 by this rank) to drive the
-- "Top 10 Products by Sales" bar chart on Page 3.


Product Rank by Profit =
RANKX(
    ALL(superstore_clean[product_name]),
    CALCULATE([Total Profit]),
    ,
    ASC
)
-- Same pattern as above, but ASC (ascending) so rank 1 = the MOST
-- negative profit, i.e. the worst-performing product.
-- Drives the "Bottom 10 Products by Profit" bar chart on Page 3.


Is Top 10 Product =
IF([Product Rank by Sales] <= 10, "Top 10", "Other")
-- Simple label used for conditional formatting / legend grouping
-- if you want to highlight Top 10 products within a larger product list visual.


Is Bottom 10 Product =
IF([Product Rank by Profit] <= 10, "Bottom 10", "Other")
-- Same idea, for the loss-making side. Used to colour Bottom 10
-- bars red consistently with the rest of the dashboard's red/green logic.


# ══════════════════════════════════════════════════════
# 8. CUSTOMER BEHAVIOUR MEASURES  [NEW]
# ══════════════════════════════════════════════════════
# Used on: Page 1 sidebar cards / Page 5 supporting context

Total Customers =
DISTINCTCOUNT(superstore_clean[customer_id])
-- Unique customer count across current filter context.
-- IMPORTANT: verify no stale slicer (e.g. a single month) is applied
-- when reading this value — a filtered context will show a misleadingly
-- low customer count. Always sanity-check with all slicers cleared.


Avg Order Value =
DIVIDE([Total Revenue], [Total Orders], 0)
-- Average revenue per distinct order. Safe-divides to avoid errors
-- if Total Orders is ever 0 in a filtered context.


Orders per Customer =
DIVIDE([Total Orders], [Total Customers], 0)
-- Rough repeat-purchase indicator. Low values (~1) suggest mostly
-- one-time buyers; higher values suggest customer retention.


# ══════════════════════════════════════════════════════
# 9. STRATEGIC INSIGHTS PAGE — DYNAMIC CARD MEASURES  [NEW]
# ══════════════════════════════════════════════════════
# Used on: Page 5 — the 4 headline stat cards
# Pattern: each measure uses SUMMARIZE + TOPN to dynamically find the
# "winning" or "losing" category/region/year, so these cards update
# automatically if the underlying data changes — no hardcoded values.

Top Region by Margin Name =
VAR RankedRegions =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[region]),
            superstore_clean[region],
            "Margin", [Profit Margin %]
        ),
        [Margin], DESC
    )
RETURN
    CONCATENATEX(RankedRegions, superstore_clean[region])
-- SUMMARIZE builds a virtual table of (region, margin) pairs across ALL regions.
-- TOPN(1, ..., DESC) picks the single row with the highest margin.
-- CONCATENATEX extracts just the region name as text for the card title.
-- Used on Page 5 Card 1: "Top Region by Margin".


Top Region by Margin Value =
VAR RankedRegions =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[region]),
            superstore_clean[region],
            "Margin", [Profit Margin %]
        ),
        [Margin], DESC
    )
RETURN
    MAXX(RankedRegions, [Margin])
-- Same ranking logic as above, but returns the margin VALUE instead of the name.
-- Used on Page 5 Card 1, displayed below/beside the region name (e.g. "26.62%").


Top Category by Profit Name =
VAR RankedCategories =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[category]),
            superstore_clean[category],
            "Profit", CALCULATE([Total Profit])
        ),
        [Profit], DESC
    )
RETURN
    CONCATENATEX(RankedCategories, superstore_clean[category])
-- Same SUMMARIZE + TOPN pattern, applied to category instead of region.
-- Used on Page 5 Card 2: "Top Category by Profit" (e.g. "Technology").


Top Category by Profit Value =
VAR RankedCategories =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[category]),
            superstore_clean[category],
            "Profit", CALCULATE([Total Profit])
        ),
        [Profit], DESC
    )
RETURN
    MAXX(RankedCategories, [Profit])
-- Returns the profit value for the top category (e.g. 664K for Technology).


Strongest YoY Growth Year =
VAR RankedYears =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[order_year]),
            superstore_clean[order_year],
            "Growth", [Revenue YoY %]
        ),
        [Growth], DESC
    )
RETURN
    MAXX(RankedYears, superstore_clean[order_year])
-- Finds which year had the single highest YoY revenue growth rate.
-- Used on Page 5 Card 3: "Strongest YoY Growth" (e.g. "2013").


Strongest YoY Growth Value =
VAR RankedYears =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[order_year]),
            superstore_clean[order_year],
            "Growth", [Revenue YoY %]
        ),
        [Growth], DESC
    )
RETURN
    MAXX(RankedYears, [Growth])
-- Returns the actual YoY % value for that strongest year (e.g. 0.272 = 27.2%).


Margin Risk Region Name =
VAR RankedRegions =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[region]),
            superstore_clean[region],
            "Margin", [Profit Margin %]
        ),
        [Margin], ASC
    )
RETURN
    CONCATENATEX(RankedRegions, superstore_clean[region])
-- Identical pattern to "Top Region by Margin Name" but ASC instead of DESC,
-- so it finds the LOWEST-margin region instead of the highest.
-- Used on Page 5 Card 4: "Margin Risk to Watch" (e.g. "Southeast Asia").


Margin Risk Region Value =
VAR RankedRegions =
    TOPN(
        1,
        SUMMARIZE(
            ALL(superstore_clean[region]),
            superstore_clean[region],
            "Margin", [Profit Margin %]
        ),
        [Margin], ASC
    )
RETURN
    MAXX(RankedRegions, [Margin])
-- Returns the margin value for the riskiest region (e.g. 0.0202 = 2.02%).


# ══════════════════════════════════════════════════════
# DATE TABLE (calculated table — not a measure)
# ══════════════════════════════════════════════════════
# Create via: Modeling → New Table → paste below

# Date =
# ADDCOLUMNS(
#     CALENDAR(DATE(2011,1,1), DATE(2014,12,31)),
#     "Year",        YEAR([Date]),
#     "Month",       MONTH([Date]),
#     "MonthName",   FORMAT([Date], "MMM"),
#     "Quarter",     "Q" & QUARTER([Date]),
#     "YearMonth",   FORMAT([Date], "YYYY-MM"),
#     "YearQuarter", FORMAT([Date], "YYYY") & " Q" & QUARTER([Date])
# )
#
# Relationship: superstore_clean[order_date] →(Many) Date[Date] (One)
# Mark as date table: select Date table → Table tools → Mark as date table → Date
